# Generated by Django 3.1.2 on 2020-10-19 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradingpost', '0003_auto_20201018_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/avatar.png', upload_to='profile_pics')),
                ('cards_owned', models.ManyToManyField(to='tradingpost.Card')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradingpost.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradingpost.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='profiles.profile')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.sale')),
            ],
        ),
    ]
