# Generated by Django 3.1.2 on 2020-10-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201019_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='profiles.sale'),
        ),
    ]
