# Generated by Django 3.1.2 on 2020-10-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('height_ft', models.IntegerField()),
                ('height_in', models.IntegerField()),
                ('jersey_number', models.IntegerField()),
                ('bats', models.CharField(max_length=30)),
                ('throws', models.CharField(max_length=30)),
                ('birth_date', models.DateTimeField()),
                ('team_name', models.CharField(max_length=30)),
                ('player_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
            ],
        ),
    ]
