# Generated by Django 3.1.2 on 2020-10-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingpost', '0002_auto_20201018_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='jersey_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
